name: aptabase_flutter
description: "Flutter SDK for Aptabase: Open Source Privacy-First and Simple
  Analytics for Mobile, Desktop and Web Apps"
version: 0.2.0-dev.1
homepage: https://aptabase.com
repository: https://github.com/aptabase/aptabase_flutter
issue_tracker: https://github.com/aptabase/aptabase_flutter/issues
topics: [aptabase, analytics, privacy, flutter, dart]
screenshots:
  - description: Insights for apps without compromising on user privacy. Build for Deskto, Mobile and Web apps.
    image: https://aptabase.com/og.png

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.0.0
  flutter:
    sdk: flutter
  http: ^1.2.0
  meta: ^1.10.0
  package_info_plus: ^4.0.0
  result_dart: ^1.1.0
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  build_version: ^2.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: ^1.21.0
  zoo_lints: ^3.1.0
