name: aptabase_flutter
description: "Flutter SDK for Aptabase: Open Source Privacy-First and Simple
  Analytics for Mobile, Desktop and Web Apps"
version: 0.2.0-dev.1
homepage: https://aptabase.com
repository: https://github.com/aptabase/aptabase_flutter
issue_tracker: https://github.com/aptabase/aptabase_flutter/issues

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.0.0
  flutter:
    sdk: flutter
  meta: ^1.10.0
  package_info_plus: ^4.0.0
  pretty_http_logger: ^1.0.3
  result_dart: ^1.1.0
  universal_io: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.8
  build_version: ^2.1.1
  flutter_test:
    sdk: flutter
  zoo_lints: ^3.1.0
